version: 2.1

orbs:  
  python: circleci/python@1.4.0

jobs:  
  build-and-test:
    executor:
      name: python/default
      tag: '3.9'
    steps:
      - checkout
      - run:
          name: Setup Virtual Env
          command: |
            virtualenv -p python3.9 venv
            echo "source ./venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

workflows:
  main: 
      jobs: 
          - build-and-test