version: 2.1

orbs:  
  python: circleci/python@1.4.0
  aws-cli: circleci/aws-cli@2.1.10

jobs:  
  build:
    executor:
      name: python/default
      tag: '3.9'
    steps:
      - checkout
      - run:
          name: Setup Virtual Env
          command: |
            virtualenv -p python3.9 venv
            echo "source ./venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run: 
          name: Create Zipfile Archive of Dependencies
          command: |
            cd venv/lib/python3.9/site-packages
            zip -r9 ../../../../function.zip . 
      - run: 
          name: Add App to Zipfile
          command: zip -g ./function.zip -r app
      - persist_to_workspace:
          root: .
          paths:
            - function.zip

  deploy: 
    executor: aws-cli/default
    steps: 
      - attach_workspace: 
          at: ./ 
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRECT_ACCESS_KEY
      - run: 
          name: Upload to S3
          command: aws s3 cp function.zip s3://coag/function.zip
      - run: 
          name: Deploy new Lambda 
          command: aws lambda update-function-code --function-name coag-lambda --s3-bucket coag --s3-key function.zip

workflows:
  version: 2
  build-and-deploy: 
      jobs: 
        - build:
            context: coag-cicd
            filters: 
              branches:
                only: 
                  - main
        - deploy: 
            context: coag-cicd
            requires: 
              - build
            filters: 
              branches:
                only: 
                  - main